baseurl = "http://seekingauthenticity.netlify.com/"
languageCode = "en-us"
title = "Jeremiah - Hugo Strata"
theme = "strata"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 5
# metaDataFormat = "yaml"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Jeremiah Valenzuela"
	description = "A test site for working with Hugo, Forestry, and Netlify"

	# Format dates with Go's time formatting
	date_format = "Monday, January 2, 2006 15:04"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "I'm **Jeremiah**, a super simple<br> responsive human<br> crafted by humans."
		# The icons will be shown if you enter your username
		twitter = "gaetawoo"
		github = "gaetawoo"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = "JJValenzuela"
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Jeremiah Valenzuela",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)",
			"Ipsum Text: [RikerIpsum](//www.rikeripsum.com)"
		]


	[params.about]
		hide  = false
		title = "I'll alert the crew. Could someone survive inside a transporter buffer for 75 years? Not if I weaken first."
		content = "That might've been one of the shortest assignments in the history of Starfleet. Congratulations - you just destroyed the Enterprise. Talk about going nowhere fast. The game's not big enough unless it scares you a little. Smooth as an android's bottom, eh, Data? Mr. Worf, you do remember how to fire phasers? I suggest you drop it, Mr. Data. In all trust, there is the possibility for betrayal. Some days you get the bear, and some days the bear gets you. Well, I'll say this for him - he's sure of himself. Why don't we just give everybody a promotion and call it a night - 'Commander'? I recommend you don't fire until you're within 40,000 kilometers. And blowing into maximum warp speed, you appeared for an instant to be in two places at once. Earl Grey tea, watercress sandwiches... and Bularian canap√©s? Are you up for promotion? Wouldn't that bring about chaos?"


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Racks"
			description = "For an android with no feelings, he sure managed to evoke them in others."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Trees"
			description = "I think you've let your personal feelings cloud your judgement."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Books"
			description = "Besides, you look good in a dress."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Steps"
			description = "I am your worst nightmare!"

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Mountains mounTAINS MOUNtains"
			description = "The unexpected is our normal routine."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Nussing Butet"
			description = "Maybe if we felt any human loss as keenly as we feel one of those close to us, human history would be far less bloody."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Commander William Riker of the Starship Enterprise. Captain, why are we out here chasing comets? Yes, absolutely, I do indeed concur, wholeheartedly! Then maybe you should consider this: if anything happens to them, Starfleet is going to want a full investigation."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0
	
[[menu.main]]
	name = "About"
	url = "about"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
