backend:
  name: github
  repo: https://github.com/gaetawoo/seekingauthenticity/ # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)
# publish_mode: editorial_workflow

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
